=== iearn-finance/yearn-meta/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses"]
}

=== iearn-finance/yearn-meta/data/strategies/Curvegusd3CRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "Curvegusd3CRVVoterProxy",
  "description": "This vault accepts deposits of [gusd3CRV](https://etherscan.io/address/0xd2967f45c4f384deea880f807be904762a3dea07) tokens obtained by supplying either DAI, USDC, USDT, (or their wrapped version: 3CRV), or GUSD to the liquidity pool on Curve [here](https://curve.fi/gusd/deposit). gusd3CRV tokens are staked in the gauge on Curve to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more gusd3CRV.",
  "addresses": ["0x9C1117cf2ED3A0F4A9F069001F517c1D511c8B53"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/voterproxy_unique/CurvealUSD3CRV-fVoterProxy.json
{
  "$schema": "strategy",
  "name": "Curve Boosts alUSD Strategy",
  "description": "This vault takes your deposited token and turns it into {{token}} by supplying liquidity on [Curve Finance](https://curve.fi/). {{token}} tokens are then staked in the gauge on Curve to earn ALCX and enhanced CRV rewards thanks to Yearn's [locked CRV boosts](https://resources.curve.fi/guides/boosting-your-crv-rewards). Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more {{token}} tokens.",
  "addresses": ["0x31CD90D60516ED18750bA49b2C9d1053190F40d9"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/CurveFRAX3CRV-fVoterProxy.json
{
  "$schema": "strategy",
  "name": "CurveFRAX3CRV-fVoterProxy",
  "description": "This vault accepts deposits of [FRAX3CRV-f](https://etherscan.io/address/0xd632f22692FaC7611d2AA1C0D552930D43CAEd3B) tokens obtained by supplying either FRAX, DAI, USDC, or USDT to the liquidity pool on Curve [here](https://www.curve.fi/frax/deposit). FRAX3CRV-f tokens are staked in the gauge on Curve to earn CRV and [FXS](https://www.coingecko.com/en/coins/frax-share) rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more FRAX3CRV-f.",
  "addresses": ["0xb622F17e1ba8C51b9BD760Fb37994a55b1e5CD85"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/CurvealUSD3CRV-fVoterProxy.json
{
  "$schema": "strategy",
  "name": "CurvealUSD3CRV-fVoterProxy",
  "description": "This vault accepts deposits of [alUSD3CRV-f](https://etherscan.io/address/0x43b4FdFD4Ff969587185cDB6f0BD875c5Fc83f8c) tokens obtained supplying either DAI, USDC, USDT (or their wrapped version: 3crv), or alUSD to the liquidity pool on Curve [here](https://curve.fi/alusd/deposit). alUSD3CRV-f tokens are staked in the gauge on Curve to earn CRV and [ALCX](https://www.coingecko.com/en/coins/alchemix) rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more alUSD3CRV-f.",
  "addresses": ["0x31CD90D60516ED18750bA49b2C9d1053190F40d9"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/ConvexbBTCsbtcCRV.json
{
  "$schema": "strategy",
  "name": "ConvexbBTC/sbtcCRV",
  "description": "Supplies bBTC/sbtcCrv to Convex Finance to earn CRV and farm CVX. Rewards are harvested, sold for more bBTC/sbtcCrv, and deposited back into the vault.",
  "addresses": ["0xE9ac8D34C546CBfdAD98F9a4546Db5fE08D01bF2"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/CurvesaCRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "CurvesaCRVVoterProxy",
  "description": "This vault accepts deposits of [saCRV](https://etherscan.io/address/0x02d341CcB60fAaf662bC0554d13778015d1b285C) tokens obtained by supplying either DAI or sUSD to the liquidity pool on Curve [here](https://www.curve.fi/saave/deposit). saCRV tokens are staked in the gauge on Curve to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more saCRV.",
  "addresses": ["0xE73817de3418bB44A4FeCeBa53Aa835333C550e7"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/v1_curvepool/StrategymUSDCurve.json
{
  "$schema": "strategy",
  "name": "mUSD Curve Strategy",
  "description": "This vault deposits {{token}} into the [mUSD/3Crv](https://www.curve.fi/3pool/deposit) on Curve Finance. The mUSD/3Crv liquidity provider tokens are then deposited into the Curve mUSD/3Crv yVault.",
  "addresses": ["0x6f1EbF5BBc5e32fffB6B3d237C3564C15134B8cF"],
  "authors": [{ "name": "orbxball", "uri": "https://twitter.com/orbxball" }]
}

=== iearn-finance/yearn-meta/data/strategies/Curvemusd3CRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "Curvemusd3CRVVoterProxy",
  "description": "This vault accepts deposits of musd3CRV tokens obtained by supplying either mUSD, DAI, USDC, USDT (or wrapped via 3Crv tokens) to the liquidity pool on Curve here. musd3CRV tokens are staked in the gauge on Curve to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more musd3CRV.",
  "addresses": ["0xf9fF7f463A7e6f43d4E65c230D3743355fC954e4"],
  "authors": []
}
