=== iearn-finance/yearn-meta/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses"]
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/v1_curvepool/StrategyTUSDypool.json
{
  "$schema": "strategy",
  "name": "TUSD yPool Strategy",
  "description": "This vault deposits {{token}} into the YPool on Curve.fi. The yCRV liquidity provider tokens are then deposited into the Curve YPool yVault.",
  "addresses": ["0xe3a711987612BFD1DAFa076506f3793c78D81558"],
  "authors": [{ "name": "orbxball", "uri": "https://twitter.com/orbxball" }]
}

=== iearn-finance/yearn-meta/data/strategies/ConvexoBTCsbtcCRV.json
{
  "$schema": "strategy",
  "name": "ConvexoBTC/sbtcCRV",
  "description": "Supplies oBTC/sbtcCRV to Convex Finance to earn CRV and farm CVX. Rewards are harvested, sold for more oBTC/sbtcCRV, and deposited back into the vault.",
  "addresses": ["0xDb2D3F149270630382D4E6B4dbCd47e665D78D76"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/ConvextbtcsbtcCrv.json
{
  "$schema": "strategy",
  "name": "Convextbtc/sbtcCrv",
  "description": "Supplies tBTC/sbtcCrv to Convex Finance to earn CRV and CVX. Rewards are harvested, sold for more tBTC/sbtcCrv, and deposited back into the vault.",
  "addresses": ["0x07fb6A53185E2F095253099A47F34CD410eB2A89"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/CurveankrCRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "CurveankrCRVVoterProxy",
  "description": "This vault accepts deposits of [ankrCRV](https://etherscan.io/address/0xaA17A236F2bAdc98DDc0Cf999AbB47D47Fc0A6Cf) tokens obtained by supplying either ETH or ankrETH to the liquidity pool on Curve [here](https://www.curve.fi/ankreth/deposit). ankrCRV tokens are staked in the gauge on Curve to earn CRV, [ANKR](https://www.coingecko.com/en/coins/ankr-network), and [ONX](https://www.coingecko.com/en/coins/onx-finance) rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more ankrCRV.",
  "addresses": ["0x32EF165F2ABbdbE7dcC25B86EdB14a2C0dc52571"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/ConvexcDAI+cUSDC.json
{
  "$schema": "strategy",
  "name": "ConvexcDAI+cUSDC",
  "description": "Supplies cDAI+cUSDC to Convex Finance to earn CRV and CVX. Rewards are harvested, sold for more cDAI+cUSDC, and deposited back into the vault.",
  "addresses": ["0x2b0b941d98848d6c9C729d944E3B1BD9C00A5529"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/Curvehusd3CRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "Curvehusd3CRVVoterProxy",
  "description": "This vault accepts deposits of husd3CRV tokens obtained by supplying either DAI, USDC, USDT (or their wrapped version: 3crv), or HUSD to the liquidity pool on Curve here. husd3CRV tokens are staked in the gauge on Curve to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more husd3CRV.",
  "addresses": ["0x5ED527A2cfC5411EB63b12E46e270b07b6813824"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/ConvexTUSD3CRV-f.json
{
  "$schema": "strategy",
  "name": "ConvexTUSD3CRV-f",
  "description": "Supplies TUSD3CRV-f to Convex Finance to earn CRV and CVX. Rewards are harvested, sold for more TUSD3CRV-f, and deposited back into the vault.",
  "addresses": ["0x270101459e9A38Db38Ba4Cb8718FfA31953A9Af3"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/StrategyRook.json
{
    "$schema": "strategy",
    "name": "Rook Reward Strategy",
    "description": "Supplies {{token}} to [KeeperDAO](https://app.keeperdao.com/) to farm ROOK. Rewards are harvested, sold for more {{token}}, and deposited back into the vault.",
    "addresses": [
        "0x2B1a6CB0168aA540ee8D853aB1d10d7A89d6351b",
        "0xB361a3E75Bc2Ae6c8A045b3A43E2B0c9aD890d48",
        "0xbC0F2FF495eE2eb74A145EDAA457FA4Fa310DAC5"
    ],
    "authors": []
  }
