=== iearn-finance/yearn-meta/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "localization": {
      "type": "object",
      "properties": {
        "en": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "fr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "es": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "de": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "pt": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "el": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "tr": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "vi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "zh": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "hi": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ja": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "id": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        },
        "ru": {
          "type": "object",
          "required": ["name", "description"],
          "properties": {
            "name": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      },
      "required": [
        "en",
        "fr",
        "es",
        "de",
        "pt",
        "el",
        "tr",
        "vi",
        "zh",
        "hi",
        "ja",
        "id",
        "ru"
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name"]
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "address"
      }
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description", "addresses"]
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/yvWBTCStratMMV1.json
{
  "$schema": "strategy",
  "name": "Mushroom Finance wBTC Strategy",
  "description": "Supplies wBTC to Mushroom Financeâ€™s wBTC Vault then to the wBTC Farm to earn MM. MM are harvested, sold for more wBTC, and re-deposited into the vault.",
  "addresses": ["0x53a65c8e238915c79a1e5C366Bc133162DBeE34f"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/Curveust3CRVVoterProxy.json
{
  "$schema": "strategy",
  "name": "Curveust3CRVVoterProxy",
  "description": "This vault accepts deposits of [ust3CRV](https://etherscan.io/address/0x94e131324b6054c0D789b190b2dAC504e4361b53) tokens obtained by supplying either UST, DAI, USDC, USDT(or wrapped via 3Crv tokens) to the liquidity pool on Curve [here](https://www.curve.fi/ust/deposit). ust3CRV tokens are staked in the gauge on Curve rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more ust3CRV.",
  "addresses": ["0xbf811462955DEeD9aaD62EFE771E34e8B5811857"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/StrategyCurveIBVoterProxy.json
{
  "$schema": "strategy",
  "name": "StrategyCurveIBVoterProxy",
  "description": "This vault accepts deposits of [ib3CRV](https://etherscan.io/address/0x5282a4eF67D9C33135340fB3289cc1711c13638C) tokens obtained by supplying either cyDAI, cyUSDC, or cyUSDT to the liquidity pool on Curve [here](https://www.curve.fi/ib/deposit) in exchange for ib3CRV tokens. ib3CRV are staked in the gauge on Curve Finance to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more ib3CRV.",
  "addresses": ["0x5148C3124B42e73CA4e15EEd1B304DB59E0F2AF7"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/StrategyMakerETHDAIDelegate ETH-C.json
{
  "$schema": "strategy",
  "name": "StrategyMakerETHDAIDelegate ETH-C",
  "description": "Locks ETH at MakerDAO via ETH-C to mint DAI. This newly minted DAI is then deposited into the v2 DAI yVault.",
  "addresses": ["0x946a03264BBa08d1F90dF1ce0bbD3394c3AB1cfa"],
  "authors": [{ "name": "orbxball", "uri": "https://twitter.com/orbxball" }]
}

=== iearn-finance/yearn-meta/data/strategies/StrategySynthetixSusdMinter.json
{
  "$schema": "strategy",
  "name": "StrategySynthetixSusdMinter",
  "description": "Stakes SNX at Synthetix to mint sUSD. **This locks rewards on staked SNX for 1 year**. The newly minted sUSD is then deposited into the v2 sUSD yVault to earn yield. Yield from sUSD and rewards from weekly fees plus vested rewards (when claimable) are swapped for more SNX and re-deposited into the vault.",
  "addresses": ["0xFB5F4E0656ebfF31743e674d324554fd185e1c4b"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/CurvecrvTricryptoVoterProxy.json
{
  "$schema": "strategy",
  "name": "CurvecrvTricryptoVoterProxy",
  "description": "This vault accepts deposits of [crvTricrypto](https://etherscan.io/address/0xcA3d75aC011BF5aD07a98d02f18225F9bD9A6BDF) tokens obtained by supplying either USDT, wBTC, or ETH to the liquidity pool on Curve [here](https://curve.fi/tricrypto/deposit) in exchange for crvTricrypto tokens. crvTricrypto are staked in the gauge on curve.finance to earn CRV rewards. Rewards are swapped for one of the underlying assets and resupplied to the liquidity pool to obtain more crvTricrypto.",
  "addresses": ["0xb9267f1427Ddb937003b9cA0Ca7716DDa4026D19"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/v1_curvepool/StrategyDAI3pool.json
{
  "$schema": "strategy",
  "name": "3pool Strategy",
  "description": "This vault deposits {{token}} into the 3Pool on [Curve Finance](https://www.curve.fi/3pool/deposit). The 3Crv liquidity provider tokens are then deposited into the Curve 3Pool yVault.",
  "addresses": ["0x9c211BFa6DC329C5E757A223Fb72F5481D676DC1"],
  "authors": []
}

=== iearn-finance/yearn-meta/data/strategies/individual_strats/StrategyIdleidleRAIYield.json
{
    "$schema": "strategy",
    "name": "Idle RAI Strategy",
    "description": "Supplies {{token}} on [Idle Finance](https://idle.finance/#/dashboard/best) to earn IDLE and RAI. Rewards are harvested, sold for more RAI, and re-deposited into the vault.",
    "addresses": ["0x5D411D2cde10e138d68517c42bE2808C90c22026"],
    "authors": []
}
