=== iearn-finance/yearn-meta/schema/token.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "token.json",
  "title": "Token",
  "description": "An underlying token of a yearn vault",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "website": {
      "type": "string"
    },
    "tokenIconOverride": {
      "type": "string"
    },
    "tokenSymbolOverride": {
      "type": "string"
    },
    "tokenNameOverride": {
      "type": "string"
    }
  },
  "required": []
}

=== iearn-finance/yearn-meta/data/tokens/1/0x9c2C8910F113181783c249d8F6Aa41b51Cde0f0c.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains ibCHF, a synthetic Swiss franc minted from the Iron Bank, and synthetic Swiss franc (sCHF) minted on the Synthetix platform.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvIBCHF",
  "tokenNameOverride": "Curve ibCHF Pool"
}

=== iearn-finance/yearn-meta/data/tokens/0xb19059ebb43466C323583928285a49f558E572Fd.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains WBTC and HBTC, a tokenized BTC custodied by Huobi.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvHBTC",
  "tokenNameOverride": "Curve HBTC Pool"
}

=== iearn-finance/yearn-meta/data/tokens/1/0x3b6831c0077a1e44ED0a21841C3bC4dC11bCE833.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains DAI, USDC, USDT, and Euro Tether (EURT). Please be aware that as crypto pools are composed of differently-priced assets, they are subject to impermanent loss.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvEURTUSD",
  "tokenNameOverride": "Curve EURT-USD Pool"
}

=== iearn-finance/yearn-meta/data/tokens/0xEd279fDD11cA84bEef15AF5D39BB4d4bEE23F0cA.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This factory metapool contains 3Crv (DAI, USDC, and USDT) and Liquity USD, a synthetic USD stablecoin collateralized with Ether.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvLUSD",
  "tokenNameOverride": "Curve LUSD Pool"
}

=== iearn-finance/yearn-meta/data/tokens/0x2fE94ea3d5d4a175184081439753DE15AeF9d614.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This metapool contains sBTC-Crv (sBTC, WBTC, and renBTC) and oBTC, an ERC-20 backed by native BTC via BoringDAO.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvOBTC",
  "tokenNameOverride": "Curve oBTC Pool"
}

=== iearn-finance/yearn-meta/data/tokens/0x5a6A4D54456819380173272A5E8E9B9904BdF41B.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This metapool contains 3Crv (DAI, USDC, and USDT) and MIM, a decentralized stablecoin collateralized with yVaults and other yield-bearing tokens on Abracadabra.",
  "website": "https://www.curve.fi/",
  "tokenSymbolOverride": "crvMIM",
  "tokenNameOverride": "Curve MIM Pool"
}
